[package]
name = "linux-syscalls"
version = "0.1.0"
edition = "2024"

[lib]
name = "linux_syscalls"
path = "src/lib.rs"

[dependencies]
libc = "0.2.177"
tokio = { version = "1.48.0", features = ["full"] }

